package project.mpp.foodservice.rest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import project.mpp.foodservice.domain.Food;
import project.mpp.foodservice.persistence.FoodRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path="/food") // This means URL's start with /demo (after Application path)
public class GetAllFood {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private FoodRepository foodRepository;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Food> getAllFood() {
        // This returns a JSON or XML with the users
        return foodRepository.findAll();
    }
}